### ISSUE TITLE
reading files with comma as decimals

### ISSUE THREAD

**Issue by amolares** [Yue-Jiang/pzfx#15]
Hi. I'm trying to read pzfx files, whose contain data using comma for decimals, with no success. Would it be possible to add a flag named dec, in read_pzfx, to indicate what kind of symbol is used for decimals?

**Comment by Yue-Jiang** [comment]
I remember fixing an issue like this, could you try the github version `remotes::install_github("Yue-Jiang/pzfx")`? https://github.com/Yue-Jiang/pzfx/issues/9
