### ISSUE TITLE
Adding a parameter for digits displayed

### ISSUE THREAD

**Issue by nickp60** [Yue-Jiang/pzfx#16]
Hi @Yue-Jiang, thanks for writing this package!  Would it be possible to add an parameter for setting the decimals displayed by default in the `write_fzfx` file? [The default of 0 ](https://github.com/Yue-Jiang/pzfx/blob/02cc3a0001be346798b8c6a39c846eefe697b1d4/R/write_pzfx.R#L174) has caused some confusion when circulating files to collaborators. Perhaps there could be some logic for using 0 if all values are coercible to ints, otherwise use more decimals either with some logic based on the actual data or via a function parameter.

**Comment by nickp60** [comment]
This isn't extensively tested but something like
```R
 ret <- lapply(seq_len(length(x_lst)), function(i) {
    this_df <- x_lst[[i]]
    # check type
    all_ints <-all(sapply(this_df[,2:ncol(this_df)], function(n){
      isTRUE(all.equal(as.integer(n), n))}))
    cols <- lapply(seq_len(ncol(this_df)), function(c) {
      structure(
        list(
          "Title"=list(colnames(this_df)[c]),
          "Subcolumn"=subcol_helper(this_df[, c, drop=TRUE])
        ),
        Width="89",
        Decimals=ifelse(all_ints, "0", "2"),
        Subcolumns="1"
      )
    })
# and so on
}

```

**Comment by Yue-Jiang** [comment]
thanks for the suggestion - i implemented an option to set number of digits in the master branch. let me know if it works for you and feel free to reopen if not. i'll prepare a cran update soonish.
