### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by pbreheny** [Yue-Jiang/pzfx#4]
Very helpful package -- it seems like most fields import and are formatted correctly, except for dates.  Instead of a date, those fields import as numeric values.  I'm guessing this is in years, since some arbitrary date?  Is it possible to import those as dates or strings?

**Comment by Yue-Jiang** [comment]
Thanks for reporting! I didn't know Prism supported dates, looks like it's something added since version 7: https://www.graphpad.com/guides/prism/7/user-guide/index.htm?xy_tables__x_represents_dates_.htm

In that case, would you mind supplying a small test file that has dates in it? That would be super helpful for me to trouble shoot. Embarrassingly I only have Prism 6 on my machine and my 30 day free trial for 8 has expired.

**Comment by pbreheny** [comment]
OK -- I e-mailed you an example file; please let me know if you do not receive it.

**Comment by Yue-Jiang** [comment]
Should be fixed on the master branch, at least with the file you provided:
```
> read_pzfx(path)
             X Var.2
1  16-Jan-2004   120
2   9-Apr-2009    64
3   1-Mar-2012    46
4  12-Apr-2012    51
5  26-Apr-2012    52
```
I'll give it another few days for more testing before closing.

**Comment by Yue-Jiang** [comment]
@pbreheny while you're here, also wanted to personally thank you for the excellent BIOS 7210 material - I owe a large portion of my understanding in survival analysis to the course material you made available. Much appreciated!

**Comment by pbreheny** [comment]
Great!  This is working perfectly for me -- both for the file I sent you and for other files.  Just a suggestion: you might consider an option to either import dates as strings or as numeric values.  For this particular application, I needed the actual dates, but in many cases, the numeric values would be more convenient.

Survival: You're welcome!  Glad to hear you found the material helpful.

**Comment by Yue-Jiang** [comment]
Sounds good - I added an option "date_x" that allows user to choose to import dates in X column as numeric value (I believe it's years from the first observation), character or both. Feel free to give it a try!
